LOAD DATA
INFILE 'C:\Users\sathegde\Desktop\test\dataset.csv'
INSERT INTO TABLE PY_test1
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
YEAR1,
INDUSTRY_AGGREGATION_NZSIOC,
INDUSTRY_CODE_NZSIOC,
INDUSTRY_NAME_NZSIOC,
UNITS,
VARIABLE_CODE,
VARIABLE_NAME,
VARIABLE_CATEGORY,
VALUE,
INDUSTRY_CODE_ANZSIC06
)